# NUMPY

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.26.4


In [4]:
mylist = np.array([1, 2, 3, 4, 5])
mylist = mylist * 2
print(mylist)
print(type(mylist))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


## Multidimensional Array

### 1D Array

In [5]:
import numpy as np
mylist = np.array(['A', 'B', 'C', 'D', 'E'])
print(mylist.ndim)

1


### 2D Array

In [6]:
import numpy as np
mylist = np.array([
                ['A', 'B', 'C', 'D', 'E'],
                ['F', 'G', 'H', 'I', 'J']
                   ])
print(mylist.ndim)
print(mylist.shape)# Rows and Columns

2
(2, 5)


#### 3D Array

In [7]:
import numpy as np
mylist = np.array([
    [['A', 'B', 'C', 'D', 'E'],['F', 'G', 'H', 'I', 'J'], ['K', 'L', 'M', 'N', 'O']],
    [['P', 'Q', 'R', 'S', 'T'],['U', 'V', 'W', 'X', 'Y'], ['Z', 'a', 'b', 'c', 'd']],
    [['e', 'f', 'g', 'h', 'i'],['j', 'k', 'l', 'm', 'n'], ['o', 'p', 'q', 'r', 's']]            
                   ])
print(mylist.ndim)
print(mylist.shape)# Depth, Rows and Columns

3
(3, 3, 5)


In [8]:
#Multidimensional Indexing
word = mylist[1,0,0] +mylist[1,1,0] + mylist[1,0,3] + mylist[1,0,3] + mylist[1,1,4] 
print(word)

PUSSY


## Slicing

In [9]:
import numpy as np
mylist = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12], 
                   [13, 14, 15, 16],
                   [17, 18, 19, 20]])

# array[start:stop:step]
print(mylist[::2]) # Slicing

[[ 1  2  3  4]
 [ 9 10 11 12]
 [17 18 19 20]]


In [10]:
#Reverse the array
print(mylist[::-1])

[[17 18 19 20]
 [13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [11]:
#Selecting a column
print(mylist[:,1])

[ 2  6 10 14 18]


In [12]:
#Selecting alternate columns
print(mylist[:,1::2])

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


In [13]:
print(mylist[3:,:2])

[[13 14]
 [17 18]]


## Arithmetic

In [ ]:
import numpy as np
#Sclar arithmetic
mylist = np.array([1,2,3])
print(mylist + 2)
print(mylist - 2)
print(mylist / 2)
print(mylist * 2)
print(mylist ** 2)

[3 4 5]
[-1  0  1]
[0.5 1.  1.5]
[2 4 6]
[1 4 9]


In [ ]:
import numpy as np
#Vector Math Functions
mylist = np.array([1,2,3])
print(np.add(mylist,2))
print(np.subtract(mylist,2))
print(np.multiply(mylist,2))
print(np.divide(mylist,2))
print(np.power(mylist,2))
print(np.sqrt(mylist))
print(np.pi)


[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[1 4 9]
[1.         1.41421356 1.73205081]
3.141592653589793


In [16]:
radii = np.array([1,2,3])
print(np.pi * radii**2)

[ 3.14159265 12.56637061 28.27433388]


In [17]:
#Element-wise arithmetic
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
#Comparison Operators
scores = np.array([85, 90, 78, 92, 88])
print(scores == 100)
print(scores >= 60)
print(scores < 60)
print(scores != 85)

[False False False False False]
[ True  True  True  True  True]
[False False False False False]
[False  True  True  True  True]


In [19]:
scores[scores<=85] = 0
print(scores)

[ 0 90  0 92 88]


## Broadcasting

**Dimensions are compatible if: They are equal, or One of them is 1, which means it can be broadcast (stretched) to match the other.**

In [ ]:
import numpy as np
array1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

array2 = np.array([[4],[5],[6]])

print(array1.shape)
print(array2.shape)
print(array1 * array2)

(3, 3)
(3, 1)
[[ 4  8 12]
 [20 25 30]
 [42 48 54]]


In [31]:
array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(array1.shape)
print(array2.shape)

print(array1 * array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## Aggregate Function

In [ ]:
import numpy as np
array =  np.array([[1,2,3,4,5,6,7,8,9,10]])

print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))#Index of the minimum value
print(np.argmax(array))#Index of the maximum value

55


In [35]:
array =  np.array([[1,2,3,4,5],
                   [6,7,8,9,10]])
print(np.sum(array, axis=0))#Sum of each column
print(np.sum(array, axis=1))#Sum of each row

[ 7  9 11 13 15]
[15 40]


## Filtering

In [38]:
ages = np.array([
    [18,19,17,12,11,14,16],
    [25,24,29,32,28,30,27]
    ])

teenagers = ages[ages<18]
print(teenagers)

adults = ages[(ages>=18) & (ages<65)]
print(adults)

seniors = ages[ages>=65]
print(seniors)

evens = ages[ages%2==0]
print(evens)

odds = ages[ages%2!=0] 
print(odds)

[17 12 11 14 16]
[18 19 25 24 29 32 28 30 27]
[]
[18 12 14 16 24 32 28 30]
[19 17 11 25 29 27]


In [42]:
#another way to filter
adults = np.where((ages>=18) & (ages<65), ages,0)
print(adults)

[[18 19  0  0  0  0  0]
 [25 24 29 32 28 30 27]]


## Random Numbers

In [77]:
import numpy as np
#To produce same results, you can pass a seed value like rng = np.random.default_rng(42)
rng = np.random.default_rng()
print(rng.integers(1, 10, size=(5,2)))

[[9 6]
 [3 5]
 [6 3]
 [1 3]
 [8 9]]


In [78]:
import numpy as np
rng = np.random.default_rng()
#np.random.uniform draws random floating-point samples from a continuous uniform distribution over a specified interval
print(np.random.uniform(-1,1, size=(3,3)))

[[-0.26933862  0.54922456  0.59504912]
 [-0.5793923  -0.82629561 -0.87652777]
 [-0.57729592  0.38403811  0.04028084]]


In [79]:
import numpy as np
rng = np.random.default_rng()
array = np.array([1,2,3,4,5])
rng.shuffle(array)
print(array)

[5 1 2 4 3]


In [82]:
import numpy as np

rng = np.random.default_rng()

fruits = np.array(["🍊", "🍉", "🍈","🍇","🥥", "🥝"])
fruit = rng.choice(fruits, size = (3,3))
print(fruit)

[['🥥' '🍉' '🍊']
 ['🍈' '🍈' '🥥']
 ['🥥' '🥝' '🥝']]
